config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from ckeditor_uploader import views as ckeditor_views
from django.contrib.admin.views.decorators import staff_member_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls')),
    path('course/', include('course.urls')),
    path('accounts/', include('account.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('upload/', staff_member_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('__debug__/', include('debug_toolbar.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/urls.py
from django.urls import path
from . import views

from quiz import views as quiz_views

app_name = 'course'

urlpatterns = [

    path('', views.course_list_view, name='course_list'),

    path('categories/', views.course_home, name="course_home"),
    path('categories/<slug:slug>/', views.course_home, name="course_cat"),
    path('categories/<slug:parent_slug>/<slug:cat_slug>', views.user_course_list_view, name="course_category_list"),

    path('<slug:course_slug>/filter',
         views.course_list_view, name='course_filter'),
    path('create/', views.course_create_view, name='course_create'),
    path('detail/<slug:slug>/', views.course_detail_view, name='course_detail'),
    path('htmx/detail/<int:pk>/', views.course_include_detail_view, name='course_include_detail'),
    path('update/<int:pk>/', views.course_update_view, name='course_update'),
    path('active/<int:pk>', views.active_or_deactive_course, name='active_or_deactive_course'),
    path('delete/<int:pk>/', views.course_delete_view, name='course_delete'),

    # module
    path('module/<int:course_id>', views.module_form, name='module_create'),
    path('module/detail/<int:pk>', views.module_detail, name='module_detail'),
    path('module/<int:pk>/update', views.module_update_view, name="module_update"),
    path('module/<int:pk>/delete', views.module_delete_view, name="module_delete"),
    path('module/<int:module_id>/content/<model_name>/create', views.content_create_update_view,
         name="module_content_create"),
    path('module/<int:module_id>/content/<model_name>/<int:pk>/update', views.content_create_update_view,
         name="module_content_update"),
    path('module/<module_id>/<content_id>/detail/<item_id>/', views.content_detail_view, name='module_content_detail'),
    path('module/content/<int:pk>/delete', views.content_delete_view, name='module_content_delete'),

    # module quiz 
    path('module/<module_id>/create/quiz', views.module_create_quiz, name='module_quiz_create'),
    path('module/<module_id>/update/quiz/<quiz_id>', views.module_create_quiz, name='module_quiz_update'),
    path('module/<quiz_id>/detail/quiz/<module_id>', quiz_views.htmx_quiz_detail_view, name='module_quiz_detail'),

    # users paths

    path('user/detail/<int:pk>/', views.user_course_detail, name="user_course_detail"),
    path('user/courses', views.course_categories, name='user_course_list'),
    path('user/<slug:slug>', views.course_categories, name='user_course_categories'),
    path('user/module/detail/<int:pk>', views.module_detail_view, name='user_module_detail_view'),

    # fetch api

]

quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    # path('manage/'),
    path('testlar/', views.quiz_home, name="quiz_home"),
    path('test/<slug:slug>/', views.quiz_home, name="quiz_cat"),
    path('test/user/statistics', views.ResultApiView.as_view(), name='statistics_user'),
    path('test/<slug:slug>/<slug:quiz_slug>', views.user_quiz_list_view, name="user_quiz_list_view"),

    path('test/detail/<int:pk>/', views.user_quiz_detail, name="user_quiz_detail"),
    path('test/<int:pk>/start/', views.quiz_start, name="user_quiz_start"),
    path('test/<int:pk>/start/data', views.quiz_data_view, name="quiz_data"),
    path('test/<int:pk>/start/save', views.quiz_save, name="quiz_save"),
    path('test/<int:pk>/start/fetch', views.FetchApiView.as_view(), name="fetch"),
    # path('test/<int:pk>/save/', views.quiz_start, name="user_quiz_save"),

    path('test/create', views.quiz_create_view, name='quiz_create_view'),
    path('quiz_list/', views.quiz_list_view, name='quiz_list'),
    path('test/<int:pk>', views.quiz_detail_view, name='quiz_detail'),

    # htmx urls
    path('htmx/test/<int:pk>', views.htmx_quiz_detail_view, name='htmx_quiz_detail'),
    path('htmx/test/<int:pk>/delete', views.quiz_delete_view, name='quiz_delete'),
    path('htmx/test/<int:pk>/update', views.update_quiz, name='quiz_update'),
    path('htmx/test/<int:pk>/active', views.active_or_deactive, name='quiz_active_or_deactive'),
    path('htmx/create/question/<quiz_id>', views.question_form, name='create_question'),
    path('htmx/create/question/exel/<quiz_id>', views.export_question_excel, name='create_question_with_excel'),
    path('update/question/<question_id>', views.update_question, name='update_question'),
    path('delete/question/<question_id>', views.delete_question, name='delete_question'),

    # statistics user
    # manage
    path('manage/', views.manage_dashboard, name='manage_dashboard'),
    path('manage/statistics', views.statistics, name='manage_statistics'),
    path('manage/employers', views.employers, name='manage_employers'),
    path('manage/organization', views.organizations, name='manage_organizations'),
    path('api/manage/dashboard/info', views.quiz_dashboard_info, name='api_dashboard_info'),
    path('api/manage/statistics/org', views.statistics_org_api, name='statistics_org_api'),

]

course/forms.py
from django import forms
from .models import Course, Category, Module
from quiz.models import Quiz
from mptt.forms import TreeNodeChoiceField
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify


class CourseForm(forms.ModelForm):
    subject = TreeNodeChoiceField(label=_("Bo'lim"),queryset=Category.objects.all())
    title = forms.CharField(label=_("Kurs nomi"))

    class Meta:
        model = Course
        fields = ['subject', 'title', 'active']

    # def save(self, commit=True):
    #     instance = super().save(commit=False)
    #     cd = self.cleaned_data
    #     title = cd['title']
    #     instance.slug = slugify(title)
    #     return instance


class ModuleForm(forms.ModelForm):
    course = forms.ModelChoiceField(
        queryset=Course.objects.all(), widget=forms.HiddenInput)
    title = forms.CharField(label=_("Mavzu Nomi"))
    parent = forms.ModelChoiceField(queryset=Module.objects.filter(parent__isnull=True), required=False)

    class Meta:
        model = Module
        fields = ['course', 'title', 'parent']

    def __init__(self, course=None, *args, **kwargs):
        super(ModuleForm, self).__init__(*args, **kwargs)
        if course:
            self.fields['parent'].queryset = Module.objects.filter(course=course, parent__isnull=True)


class ModuleQuizForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(), widget=forms.HiddenInput)
    course = forms.ModelChoiceField(
        queryset=Course.objects.all(), widget=forms.HiddenInput)
    module = forms.ModelChoiceField(
        queryset=Module.objects.all(), widget=forms.HiddenInput)

    class Meta:
        model = Quiz
        fields = ['category', 'course', 'module',
                  'number_of_questions', 'score_to_pass', 'time']

course/views.py
import json
import urllib

import pytz
import redis
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django.conf import settings
from django.contrib.auth.decorators import permission_required
from django.db.models import F, OuterRef, Count, Q, Avg
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.base import TemplateResponseMixin, View, TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib import messages

from account.utils.recent_activity import RecentActivity
from .models import Course, Category, Module, Content, Text
from .forms import CourseForm, ModuleForm, ModuleQuizForm
from quiz.models import Question, Quiz, Result, Answer

from django.forms.models import modelform_factory
from django.apps import apps

from braces.views import CsrfExemptMixin, JsonRequestResponseMixin
from ckeditor.widgets import CKEditorWidget
from django.utils.text import slugify
from datetime import datetime

r = redis.Redis(
    host=settings.REDIS_HOST,
    db=settings.REDIS_DB,
    port=settings.REDIS_PORT
)

r.keys()


class CourseHomeView(LoginRequiredMixin, TemplateView):
    template_name = 'course/course_home.html'

    def get(self, request, slug=None, *args, **kwargs):
        categories = Category.objects.all()
        quiz = None
        if slug is not None:
            cat = Category.objects.get(slug=slug)
            categories = cat.get_children()

        return self.render_to_response({
            'object_list': categories,
            'quiz': quiz
        })


course_home = CourseHomeView.as_view()


class CourseListView(LoginRequiredMixin, TemplateResponseMixin, View):
    template_name = 'course/dashboard/course_list.html'

    # def get(self, request, slug=None, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     if slug is not None:
    #         context['object_list'] = self.get_queryset().filter(
    #             subject__slug=slug)

    #     return self.render_to_response(context)

    def get(self, request):
        object_list = Course.objects.select_related('subject', 'subject__parent').prefetch_related('modules')
        return self.render_to_response({
            'object_list': object_list
        })

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['object_list'] = Course.objects.filter(
                subject__slug=kwargs['slug'])
        except:
            pass

        return context


course_list_view = CourseListView.as_view()


class CourseDetailView(DetailView):
    model = Course
    template_name = 'course/dashboard/manage/course_detail.html'
    slug_url_kwarg = 'slug'

    def get_queryset(self):
        return super().get_queryset().select_related('subject')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.object = self.get_object()
        modules = Module.objects.filter(course=self.object).select_related('parent')
        context['modules'] = modules
        return context


course_detail_view = CourseDetailView.as_view()


class CourseCreateView(LoginRequiredMixin, CreateView):
    model = Course
    template_name = 'course/dashboard/manage/course_create.html'
    form_class = CourseForm
    success_url = reverse_lazy('course:course_list')

    def form_valid(self, form):
        form.instance.slug = slugify(form.cleaned_data['title'])
        return super().form_valid(form)


course_create_view = CourseCreateView.as_view()


class CourseUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    permission_required = 'course.view_course'
    model = Course
    template_name = 'course/dashboard/manage/course_form.html'
    fields = ['subject', 'title', 'active']

    def form_valid(self, form):
        self.object = form.save()
        context = {
            'object': self.object
        }
        return render(self.request, 'course/dashboard/manage/include_course_detail.html', context)


course_update_view = CourseUpdateView.as_view()


class CourseIncludeDetail(PermissionRequiredMixin, LoginRequiredMixin, DetailView):
    permission_required = 'course.view_course'
    model = Course
    template_name = 'course/dashboard/manage/include_course_detail.html'


course_include_detail_view = CourseIncludeDetail.as_view()


@permission_required('course.view_course')
def active_or_deactive_course(request, pk):
    object = get_object_or_404(Course, pk=pk)
    if object.active:
        object.active = False
        object.save()
    else:
        object.active = True
        object.save()
    return render(request, 'course/dashboard/manage/active_or_deactive_course.html', context={'object': object})


class CourseDeleteView(LoginRequiredMixin, DeleteView):
    model = Course
    template_name = 'course/dashboard/manage/course_delete.html'
    success_url = reverse_lazy('course:course_list')


course_delete_view = CourseDeleteView.as_view()


class ModuleCreateUpdateView(LoginRequiredMixin, TemplateResponseMixin, View):
    template_name = 'course/dashboard/manage/module_form.html'

    def get(self, request, course_id=None, module_id=None, *args, **kwargs):
        course = get_object_or_404(Course, pk=course_id)
        if module_id is not None:
            module = get_object_or_404(Module, pk=module_id)
            form = ModuleForm(instance=module)
            return self.render_to_response(
                {'form': form,
                 'course': course
                 }
            )
        else:
            form = ModuleForm(initial={'course': course}, course=course)
            return self.render_to_response(
                {'form': form,
                 'course': course
                 }
            )

    def post(self, request, course_id=None, module_id=None):
        course = get_object_or_404(Course, pk=course_id)
        form = ModuleForm(data=request.POST)
        if form.is_valid():
            obj = form.save()
            return HttpResponseRedirect(reverse('course:course_detail', kwargs={'slug': course.slug}))


module_form = ModuleCreateUpdateView.as_view()


class ModuleUpdateView(LoginRequiredMixin, UpdateView):
    model = Module
    form_class = ModuleForm
    template_name = 'course/dashboard/manage/module_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        self.object = self.get_object()
        context['course'] = self.object.course
        return context

    def get_success_url(self):
        print(self.object)
        return reverse('course:course_detail', kwargs={'slug': (self.object.course.slug)})


module_update_view = ModuleUpdateView.as_view()


class ModuleDeleteView(LoginRequiredMixin, DeleteView):
    model = Module
    template_name = 'course/dashboard/manage/module_delete.html'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.course = self.object.course
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        print(self.course.slug)
        return reverse('course:course_detail', args=(self.course.slug,))


module_delete_view = ModuleDeleteView.as_view()


class ModuleDetailView(LoginRequiredMixin, TemplateView):
    # model = Module
    template_name = 'course/dashboard/pages/detail_module.html'

    def get(self, request, pk):
        module = get_object_or_404(Module, pk=pk)
        modules = Module.objects.select_related('parent', 'course').filter(course=module.course)

        return self.render_to_response({
            "object": module,
            'modules': modules
        })

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data()
    #     object = self.get_object()
    #     context['modules'] = Module.objects.prefetch_related('contents__content_type').select_related('course', 'parent').filter(course=object.course)
    #     return context


module_detail = ModuleDetailView.as_view()


class ContentCreateUpdateView(LoginRequiredMixin, TemplateResponseMixin, View):
    module = None
    model = None
    obj = None
    template_name = 'course/dashboard/manage/content/content-form.html'

    def get_model(self, model_name):
        if model_name in ['video', 'text', 'image', 'file']:
            return apps.get_model(app_label='course', model_name=model_name)

    def get_form(self, model, *args, **kwrags):
        if model is Text:
            Form = modelform_factory(model, exclude=[
                'created',
                'updated',
                'order',
                # 'title'
            ], widgets={'content': CKEditorUploadingWidget()})
        else:
            Form = modelform_factory(model, exclude=[
                'created',
                'updated',
                'order'
            ])

        return Form(*args, **kwrags)

    def dispatch(self, request, module_id, model_name, pk=None, *args, **kwargs):
        self.module = get_object_or_404(Module, pk=module_id)
        self.model = self.get_model(model_name)
        print(request.method, pk)
        if pk:
            self.obj = get_object_or_404(self.model, id=pk)
        return super().dispatch(request, module_id, model_name, pk, *args, **kwargs)

    def get(self, request, module_id, model_name, id=None):
        form = self.get_form(self.model, instance=self.obj)
        return self.render_to_response({'form': form,
                                        'object': self.obj,
                                        'modul_id': module_id,

course/templates/course/dashboard/pages/detail_module.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load course %}

{% block content %}
    <div class="pagetitle">
        <h1>{{ object.title }}</h1>
        {% for message in messages %}
            <div class="col-lg-3 alert alert-success alert-dismissible fade show" role="alert">
                {% comment %} <h4 class="alert-heading">{{message}}</h4> {% endcomment %}
                <p>{{ message }}</p>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item "><a href="{% url 'course:course_list' %}">Kurslar</a></li>
                <li class="breadcrumb-item "><a
                        href="{% url 'course:course_detail' object.course.slug %}">{{ object.course }}</a></li>
                <li class="breadcrumb-item active">{{ object.title|capfirst }}</li>
            </ol>
        </nav>

    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <h3>Test block</h3>
                    {% if not object.quizs_module.first %}
                        <button hx-get="{% url 'course:module_quiz_create' object.id %}"
                                hx-target="#card-body__form-test"
                                hx-swap="innerHTML" class="btn btn-outline-dark"> test qo'shish
                        </button>
                    {% endif %}


                </div>
                <div class="card-body">
                    <div id="card-body__form-test">

                    </div>
                    <div class="row pt-2">
                        {% for object in object.quizs_module.all %}
                            <div class="col-lg-4" id="quiz_detail-{{ object.id }}">
                                {% include 'dashboard/manage/quiz_detail.html' %}
                            </div>
                        {% endfor %}
                    </div>

                </div>
            </div>
        </div>
        <div class="col-lg-8">

            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <h3>{{ object.title }}</h3>
                    <div class="block_content d-flex justify-content-between gap-2">

                        <div class="action_content">
                            <button class="btn btn-outline-dark" hx-target="#card-body__form" hx-swap="innerHTML"
                                    hx-get="{% url 'course:module_content_create' object.id 'text' %}"><i
                                    class="bi bi-card-text"></i> Text
                            </button>
                        </div>
                        <div class="action_content">
                            <button class="btn btn-outline-dark" hx-target="#card-body__form" hx-swap="innerHTML"
                                    hx-get="{% url 'course:module_content_create' object.id 'image' %}"><i
                                    class="bi bi-card-image"></i> Rasm
                            </button>
                        </div>
                        <div class="action_content">
                            <button class="btn btn-outline-dark" hx-target="#card-body__form" hx-swap="innerHTML"
                                    hx-get="{% url 'course:module_content_create' object.id 'video' %}"><i
                                    class="bi bi-youtube"></i> Video
                            </button>
                        </div>
                        <div class="action_content">
                            <button class="btn btn-outline-dark" hx-target="#card-body__form" hx-swap="innerHTML"
                                    hx-get="{% url 'course:module_content_create' object.id 'file' %}"><i
                                    class="bi bi-file-earmark-plus"></i> File
                            </button>
                        </div>
                    </div>
                </div>
                <div class="card-body">

                    <div id="card-body" id="card-body">
                        <div id="card-body__form">

                        </div>
                        {% with user.is_authenticated as auth %}
                            {% for content in object.contents.all %}
                                <div id="content-item-{{ content.item.id }}">
                                    <p>
                                        {{ content.item.render }}
                                    </p>
                                    {% if auth %}
                                        <div class="d-flex justify-content-end gap-3">
                                            <button class="btn btn-warning"
                                                    hx-target="#content-item-{{ content.item.id }}"
                                                    hx-swap="outerHTML"
                                                    hx-get="{% url 'course:module_content_update' object.id content.item|model_name content.item.id %}"
                                            >update
                                            </button>
                                            <button class="btn btn-danger"
                                                    hx-target="#content-item-{{ content.item.id }}"
                                                    hx-swap="outerHTML"
                                                    hx-get="{% url 'course:module_content_delete' content.id %}"
                                            > delete
                                            </button>
                                        </div>
                                    {% endif %}
                                </div>
                                {#                                <p id="content-{{ content.id }}">#}
                                {#                                    {{ content.item.render }}#}
                                {##}
                                {#                                </p>#}
                                <hr>
                            {% endfor %}
                        {% endwith %}
                    </div>
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
        <div class="col-lg-4 ">
            <div class="card">
                <div class="card-header">
                    <h3>Mavzular</h3>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        {% for module in modules %}
                            {% if not module.parent %}
                                <li class="list-group-item fs-4">
                                    <a class="text-dark" href="{% url 'course:module_detail' module.id %}">
                                        {{ module.title }}</a>
                                </li>
                            {% else %}
                                <li class="list-group-item">
                                    <a class="text-dark" href="{% url 'course:module_detail' module.id %}">
                                        <span>{{ module.order|add:1 }}</span>) {{ module.title }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

{% block include_js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5sortable/0.13.3/
html5sortable.min.js"></script>
{% endblock include_js %}