config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from ckeditor_uploader import views as ckeditor_views
from django.contrib.admin.views.decorators import staff_member_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls')),
    path('course/', include('course.urls')),
    path('accounts/', include('account.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('upload/', staff_member_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('__debug__/', include('debug_toolbar.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/urls.py
from django.urls import path
from . import views

from quiz import views as quiz_views

app_name = 'course'

urlpatterns = [

    path('', views.course_list_view, name='course_list'),

    path('categories/', views.course_home, name="course_home"),
    path('categories/<slug:slug>/', views.course_home, name="course_cat"),
    path('categories/<slug:parent_slug>/<slug:cat_slug>', views.user_course_list_view, name="course_category_list"),

    path('<slug:course_slug>/filter',
         views.course_list_view, name='course_filter'),
    path('create/', views.course_create_view, name='course_create'),
    path('detail/<slug:slug>/', views.course_detail_view, name='course_detail'),
    path('htmx/detail/<int:pk>/', views.course_include_detail_view, name='course_include_detail'),
    path('update/<int:pk>/', views.course_update_view, name='course_update'),
    path('active/<int:pk>', views.active_or_deactive_course, name='active_or_deactive_course'),
    path('delete/<int:pk>/', views.course_delete_view, name='course_delete'),

    # module
    path('module/<int:course_id>', views.module_form, name='module_create'),
    path('module/detail/<int:pk>', views.module_detail, name='module_detail'),
    path('module/<int:pk>/update', views.module_update_view, name="module_update"),
    path('module/<int:pk>/delete', views.module_delete_view, name="module_delete"),
    path('module/<int:module_id>/content/<model_name>/create', views.content_create_update_view,
         name="module_content_create"),
    path('module/<int:module_id>/content/<model_name>/<int:pk>/update', views.content_create_update_view,
         name="module_content_update"),
    path('module/<module_id>/<content_id>/detail/<item_id>/', views.content_detail_view, name='module_content_detail'),
    path('module/content/<int:pk>/delete', views.content_delete_view, name='module_content_delete'),

    # module quiz 
    path('module/<module_id>/create/quiz', views.module_create_quiz, name='module_quiz_create'),
    path('module/<module_id>/update/quiz/<quiz_id>', views.module_create_quiz, name='module_quiz_update'),
    path('module/<quiz_id>/detail/quiz/<module_id>', quiz_views.htmx_quiz_detail_view, name='module_quiz_detail'),

    # users paths

    path('user/detail/<int:pk>/', views.user_course_detail, name="user_course_detail"),
    path('user/courses', views.course_categories, name='user_course_list'),
    path('user/<slug:slug>', views.course_categories, name='user_course_categories'),
    path('user/module/detail/<int:pk>', views.module_detail_view, name='user_module_detail_view'),

    # fetch api

]

quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    # path('manage/'),
    path('testlar/', views.quiz_home, name="quiz_home"),
    path('test/<slug:slug>/', views.quiz_home, name="quiz_cat"),
    path('test/user/statistics', views.ResultApiView.as_view(), name='statistics_user'),
    path('test/<slug:slug>/<slug:quiz_slug>', views.user_quiz_list_view, name="user_quiz_list_view"),

    path('test/detail/<int:pk>/', views.user_quiz_detail, name="user_quiz_detail"),
    path('test/<int:pk>/start/', views.quiz_start, name="user_quiz_start"),
    path('test/<int:pk>/start/data', views.quiz_data_view, name="quiz_data"),
    path('test/<int:pk>/start/save', views.quiz_save, name="quiz_save"),
    path('test/<int:pk>/start/fetch', views.FetchApiView.as_view(), name="fetch"),
    # path('test/<int:pk>/save/', views.quiz_start, name="user_quiz_save"),

    path('test/create', views.quiz_create_view, name='quiz_create_view'),
    path('quiz_list/', views.quiz_list_view, name='quiz_list'),
    path('test/<int:pk>', views.quiz_detail_view, name='quiz_detail'),

    # htmx urls
    path('htmx/test/<int:pk>', views.htmx_quiz_detail_view, name='htmx_quiz_detail'),
    path('htmx/test/<int:pk>/delete', views.quiz_delete_view, name='quiz_delete'),
    path('htmx/test/<int:pk>/update', views.update_quiz, name='quiz_update'),
    path('htmx/test/<int:pk>/active', views.active_or_deactive, name='quiz_active_or_deactive'),
    path('htmx/create/question/<quiz_id>', views.question_form, name='create_question'),
    path('htmx/create/question/exel/<quiz_id>', views.export_question_excel, name='create_question_with_excel'),
    path('update/question/<question_id>', views.update_question, name='update_question'),
    path('delete/question/<question_id>', views.delete_question, name='delete_question'),

    # statistics user
    # manage
    path('manage/', views.manage_dashboard, name='manage_dashboard'),
    path('manage/statistics', views.statistics, name='manage_statistics'),
    path('manage/employers', views.employers, name='manage_employers'),
    path('manage/organization', views.organizations, name='manage_organizations'),
    path('api/manage/dashboard/info', views.quiz_dashboard_info, name='api_dashboard_info'),
    path('api/manage/statistics/org', views.statistics_org_api, name='statistics_org_api'),

]

quiz/models.py
from django.db import models
import os
import random
from io import BytesIO

import uuid as uuid
from django.db import models
import qrcode
from io import BytesIO
from django.core.files import File as F
from PIL import ImageDraw, Image as Img
from django.urls import reverse

from quiz.fields import OrderField
from account.models import CustomUser
from mptt.models import MPTTModel, TreeForeignKey
from django.utils.translation import gettext_lazy as _

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class Category(MPTTModel):
    name = models.CharField(
        verbose_name=_("Category Name"),
        help_text=_("Required and unique"),
        max_length=255,
    )
    slug = models.SlugField(verbose_name=_(
        "Category safe URL"), max_length=255, unique=True)
    parent = TreeForeignKey("self", on_delete=models.CASCADE,
                            null=True, blank=True, related_name="children")
    is_active = models.BooleanField(default=True)
    icon = models.ImageField()

    class MPTTMeta:
        order_insertion_by = ["name"]

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def icon_url(self):
        return self.icon

    def __str__(self):
        return self.name


class Quiz(models.Model):
    yakuniy = 'yk'
    sinov_test = 'st'
    title_choices = [
        (yakuniy, 'Yakuniy nazorat'),
        (sinov_test, 'Sinov test'),
    ]

    category = TreeForeignKey("quiz.Category", on_delete=models.CASCADE, null=True, blank=True,
                              related_name='quizs',
                              verbose_name='Bo\'lim', help_text="Bo'limni tanlang")
    course = models.ForeignKey(
        "course.Course", on_delete=models.CASCADE, related_name='quizs_course', blank=True, null=True)
    module = models.ForeignKey("course.Module", verbose_name=_(
        "module"), on_delete=models.CASCADE, blank=True, null=True, related_name='quizs_module')

    title = models.CharField(verbose_name='Sarlavha', choices=title_choices, default=yakuniy,
                             max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    number_of_questions = models.IntegerField(
        verbose_name="Test savollari soni", blank=True)
    score_to_pass = models.IntegerField(
        verbose_name='o\'tish bali', help_text="O'tish uchun eng past ball (1 ~ 100 oralig'ida)")
    time = models.IntegerField(
        verbose_name='test vaqti', help_text="test yechish uchun vaqt davomiyligi")
    created = models.DateTimeField(auto_now_add=True)
    period_date = models.DateTimeField(blank=True, null=True)
    active = models.BooleanField(default=False)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    #
    def __str__(self):
        return f"{self.category}"

    def get_questions(self):
        questions = list(self.questions.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    # def save(self, *args, **kwargs):
    #     qrcode_img = qrcode.make(f"")
    #     canvas = Img.new('RGB', (450, 450), 'white')
    #     draw = ImageDraw.Draw(canvas)
    #     canvas.paste(qrcode_img)
    #     fname = f"{str(self.course).strip(' ')}" + '.png'
    #     buffer = BytesIO()
    #     canvas.save(buffer, 'PNG')
    #     self.qr_photo.save(fname, F(buffer), save=False)
    #     canvas.close()
    #     super().save(*args, **kwargs)

    class Meta:
        ordering = ['category', 'course', 'module']


class Question(models.Model):
    quiz = models.ForeignKey(
        Quiz, on_delete=models.CASCADE, related_name='questions')
    # text=CKEditor5Field('Text', config_name='extends')
    # text = RichTextUploadingField()
    text = models.TextField(blank=True, null=True)
    uuid = models.UUIDField(default=uuid.uuid4(), editable=False, unique=True)

    created = models.DateTimeField(auto_now_add=True)
    order = OrderField(blank=True, for_fields=['quiz'], null=True)

    # def __str__(self):
    #     return f"{self.text}"

    def get_answers(self):
        answers = list(self.answers.all())
        random.shuffle(answers)
        return answers

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['created']


class Answer(models.Model):
    # text=CKEditor5Field('Text', config_name='extends')
    # text = RichTextUploadingField()
    text = models.TextField(blank=True, null=True)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name='answers')
    created = models.DateTimeField(auto_now_add=True)
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    order = OrderField(blank=True, for_fields=['question'], null=True)

    def __str__(self):
        return f'savol: {self.question.text} - javob: {self.correct}'

    class Meta:
        ordering = ['-created']


class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE,
                             related_name='result', related_query_name='result')
    user = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name='result')
    score = models.FloatField()
    attempts = models.IntegerField(
        verbose_name='urinishlar soni', help_text='Urinishlar soni', default=1)
    date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user}: result {self.score}"

    def result(self):
        return f"{self.user}: result {self.score}"


# class Sertificate(models.Model):
#     def content_image_name(instance, filename):
#         return '/'.join([f'{instance.course}', str(instance.student), filename])

#     uuid = models.UUIDField(default=uuid.uuid4, editable=False)
#     # course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='sertificate')
#     user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='sertificate',
#                                 related_query_name='sertificate')
#     qr_photo = models.ImageField(editable=False, upload_to=content_image_name, blank=True)
#     created = models.DateField(auto_now_add=True)

#     def get_absolute_url(self):
#         return reverse('account:sertificate', kwargs={'uuid': self.uuid})

#     def save(self, *args, **kwargs):
#         try:
#             if len(self.qr_photo) > 0:
#                 os.remove(self.qr_photo.path)
#         except:
#             pass

#         qrcode_img = qrcode.make(f"{self.get_absolute_url()}")
#         canvas = Img.new('RGB', (450, 450), 'white')
#         draw = ImageDraw.Draw(canvas)
#         canvas.paste(qrcode_img)
#         fname = f"{str(self.student).strip(' ')}" + '.png'
#         buffer = BytesIO()
#         canvas.save(buffer, 'PNG')
#         self.qr_photo.save(fname, F(buffer), save=False)
#         canvas.close()
#         super().save(*args, **kwargs)

class ExcelFileUploaded(models.Model):
    excel_file = models.FileField(upload_to='excel', verbose_name='Excel File')

quiz/forms.py
from django import forms
from .models import Answer, Quiz, Question, ExcelFileUploaded
from ckeditor.widgets import CKEditorWidget
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django.utils.translation import gettext_lazy as _
from django.forms import inlineformset_factory


class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ['category', 'title', 'number_of_questions', 'score_to_pass', 'time']


class QuestionForm(forms.ModelForm):
    quiz = forms.ModelChoiceField(queryset=Quiz.objects.all(), widget=forms.HiddenInput)
    # text = forms.CharField(label=_('Savol'), widget=forms.Textarea(attrs={'rows': 3}))
    text = forms.CharField(label=_('Savol'),
                           widget=forms.Textarea(attrs={'class': 'textarea form-control', 'rows': '3'}))

    class Meta:
        model = Question
        fields = ['text', 'quiz']


class ExportExcelQuestion(forms.ModelForm):
    class Meta:
        model = ExcelFileUploaded
        fields = ['excel_file']


class AnswerForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'class': 'textarea form-control'}))
    correct = forms.CharField(widget=forms.CheckboxInput(attrs={'class': 'checkboxinput form-check-input'}))


answer_formset = inlineformset_factory(Question, Answer,
                                       AnswerForm,
                                       extra=4,
                                       max_num=4,
                                       can_delete=False,
                                       fields=['text', 'correct'], )
# widgets={
#     'correct': forms.CheckboxInput(
#         attrs={'class': 'checkboxinput form-check-input'}),
#     'text': forms.Textarea(attrs={'rows': 3, 'class': 'textarea form-control'})})

quiz/templates/quiz/_base.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'quiz/css/style.css' %}">
{% endblock %}

{% block header %}

{% endblock %}

{% block aside %}

{% endblock %}

{% block quiz %}

{% endblock %}

quiz/templates/quiz/detail.html
{% extends 'quiz/_base.html' %}
{% load static %}
{% load mptt_tags %}

{% block quiz %}
    <header>
        <div class="container">

            <div class="login">
                <ul class="root">

                    {#                        {{ object.category.get_family }}#}
                    <nav>
                        <ol class="breadcrumb">
                            {% for cat in object.category.get_family %}
                                <li class="breadcrumb-item">{{ cat }}</li>
                            {% endfor %}
                        </ol>
                    </nav>

                </ul>
                <div class="arrow_prev float-start fs-9">
                    <span id="prev">
                        <i class="bi bi-arrow-left-circle fs-1"></i>
                    </span>
                </div>
                <img src="{% static 'quiz/images/logo.png' %}" alt="">

                <div class="login-item">
                    <div class="item">

                        <div class="jumbotron">


                            <div class="">
                                <div class="">
                                    <h5 class="card-title">
                                        <h1 class="display-6">{{ quiz.category }}</h1>
                                    </h5>
                                    <hr class="my-4">
                                    <div class="responsive">
                                        <table class="table">

                                            <tr>
                                                <th>Savollar</th>
                                                <td>{{ object.number_of_questions }} ta</td>
                                            </tr>

                                            <tr>
                                                <th>O'tish bali</th>
                                                <td>{{ object.score_to_pass }}</td>
                                            </tr>

                                            <tr>
                                                <th>Vaqt</th>
                                                <td>{{ object.time }} min</td>
                                            </tr>
                                            {% if result %}
                                                <tr>
                                                    <th>Ball</th>
                                                    <td>{{ result.score }}</td>
                                                </tr>
                                                <tr>
                                                    <th>urunishlar soni</th>
                                                    <td>{{ result.attempts }}</td>
                                                </tr>
                                            {% endif %}

                                            {% if object.course %}
                                                <tr>
                                                    <th>Kurs</th>

                                                    <td>
                                                        {{ object.course }}
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <th>Dars</th>

                                                    <td>
                                                        {{ object.module }}
                                                    </td>
                                                </tr>
                                            {% endif %}
                                        </table>
                                    </div>
                                </div>

                            </div><!-- End Default Card -->


                            <a class="btn btn-primary  btn-md mt-2" href="{% url 'quiz:user_quiz_start' object.pk %}"
                               role="button">Testni boshlash</a>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </header>

{% endblock %}


{% block include_js %}
    <script>
        let prev_btn = document.getElementById('prev')
        prev_btn.addEventListener('click', () => {
            window.history.back()
        })
    </script>
{% endblock %}

quiz/templates/quiz/index.html
{% extends 'quiz/_base.html' %}
{% load static %}


{% block quiz %}
    <header>

        <div class="container">
            <div class="login">
                <img src="{% static 'quiz/images/logo.png' %}" alt="">
                <div class="login-item">
                    <div class="item">
                        <a href="{% url 'quiz:quiz_home' %}" class="link_item">Test sinovlari</a>
                        <a href="{% url 'course:course_home' %}" class="link_item">Bilimlarni oshirish</a>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

quiz/templates/quiz/quiz_start.html
{% extends 'quiz/_base.html' %}

{% load static %}

{% load mptt_tags %}

{% block quiz %}
    <header>
        <div class="container">
            <div class="login" id="login">
                <div class="login-item">
                    <div id="timer-box" class="col text-end"></div>
                    <br><br>
                    <div class="test-menu" id="list_number">
                    </div>
                    <div class="item item-test">
                        <form action="" id="quiz-form">
                            {% csrf_token %}
                            <div id="quiz-box" class="quiz_box">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block include_js %}
{#    <script>#}
{#        {% comment %} function confirmUnload(event) {#}
{#            event.preventDefault();#}
{#            event.returnValue = '';#}
{#          }#}
{#        window.addEventListener('beforeunload', confirmUnload); {% endcomment %}#}
{#        window.addEventListener('beforeunload', function(event) {#}
{#            event.preventDefault();#}
{#            event.returnValue = 'Are you sure you want to leave this page?';#}
{#            if (confirm('Are you sure you want to leave this page?')) {#}
{#              console.log('hello confirm')#}
{#            } else if(confirm('Changes you made may not be saved.')){#}
{#                console.log('reloadga keldi')#}
{#            }else {#}
{#              console.log('cancel')#}
{#            }#}
{#          });#}
{##}
{#    </script>#}
<script src="{% static 'quiz/js/quiz.js' %}" defer></script>
{% endblock %}

quiz/templates/quiz/user_quiz_list.html
{% extends 'user/base.html' %}
{% load static %}
{% load mptt_tags %}

{% block title %}
    Categories
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'user/dash/css/style.css' %}">
{% endblock %}

{% block content %}
    <div class="wrapper-dashboard bg-light">
        <div class="main-dashboard">
            <div class="top__main-dashboard ">
                <div class="profile-group__main-dashboard rounded-3">
                    <img
                            class="rounded-circle border border-4"
                            src="{{ photo }}"
                            alt="profile"
                            width="130"
                            height="130"
                    />
                    {#                    <h5 class="title__profile-group fw-bold mb-0 mt-1">Ali Barin</h5>#}
                    <p class="text__profile-group text-secondary p-2"
                       style="text-align: center">{{ organization.name }}</p>
                    <p class="text__profile-group text-secondary " style="text-align: center">{{ staff_full }}</p>
                </div>
                <div class="search-group__main-dashboard rounded-3">
                    <h3 class="text-light fw-bolder">{{ fullname }}</h3>
                    <div class="form-group search-content">
              <span class="google-icon__search-content">

              </span>
                        <input
                                type="text"
                                class="form-control bg-white bg-opacity-75 rounded-5"
                                placeholder="Поиск"
                        />
                        <div class="search-icon__search-content">
                            <img
                                    src="{% static 'assets/img/search-icon.png' %}"
                                    alt="search icon"
                                    width="30"
                            />
                        </div>
                    </div>
                </div>
            </div>
            <div class="middle__main-dashboard">
                <h3 class="title-dashboard">{{ cat }}</h3>
                <hr>
                <div class="content__middle-dashboard">

                    <div class="row">
                        {% for object in object_list %}
                            <div class="col-lg-6">
                                <div class="card">
                                    <div class="card-header">
                                        {#                                        <h5 class="card-title">Recent Activity <span>| Today</span></h5>#}
                                        <h5 class="card-title"> {{ object.get_title_display }}</h5>
                                        <code><i><b>{{ object.period_date|date }}</b></i></code>
                                    </div>
                                    <div class="card-body">
                                        <div class="responsive">
                                            <table class="table">
                                                <tr>
                                                    <th>savollar soni</th>
                                                    <td>{{ object.number_of_questions }} talik</td>
                                                </tr>
                                                <tr>
                                                    <th>O'tish bali</th>
                                                    <td>{{ object.score_to_pass }} ball</td>
                                                </tr>
                                                <tr>
                                                    <th>Test yechish muddati</th>
                                                    <td>{{ object.time }} min</td>
                                                </tr>
                                                {% if object.result.score %}
                                                    <tr>
                                                        <th>To'plangan ball</th>
                                                        <td>{{ object.result.score }} %</td>
                                                    </tr>
                                                    <tr>
                                                        <th>Urinishlar soni</th>
                                                        <td>{{ object.result.attempts }}</td>
                                                    </tr>
                                                {% endif %}


                                            </table>
                                        </div>
                                    </div>

                                    <div class="card-footer justify-content-end">
                                        {#                                        <ul class="root">#}

                                        <a class="btn btn-outline-dark"
                                           href="{% url 'quiz:user_quiz_detail' object.id %}">Testga kirish <i
                                                class="bi-chevron-double-right"></i></a>

                                        {#                        {{ object.category.get_family }}#}
                                        {#                                            <nav>#}
                                        {#                                                <ol class="breadcrumb">#}
                                        {#                                                    {% for cat in object.category.get_family %}#}
                                        {#                                                        <li class="breadcrumb-item">{{ cat }}</li>#}
                                        {#                                                    {% endfor %}#}
                                        {#                                                </ol>#}
                                        {#                                            </nav>#}


                                        {#                                        </ul>#}

                                    </div>
                                </div><!-- End Default Card -->

                            </div>



                        {% endfor %}
                    </div>


                </div>
            </div>
        </div>
        {% include 'dashboard/include/__sidebar.html' %}
    </div>
{% endblock %}

{% block include_js %}

    <script>
        console.log('hello')
        const url = '{% url 'quiz:statistics_user' %}'
        var options = {
            method: 'GET',
            mode: 'same-origin',
            headers: {
                "Content-Type": "application/json",

            }
        }
        fetch(url, options)
            .then(response => response.json())
            .then(data => {
                console.log(data)
                new Chart(document.querySelector('#barChart'), {
                    type: 'bar',
                    data: {
                        labels: data.labels,
                        datasets: [{
                            label: "O'zlashtirish",
                            data: data.data,
                            backgroundColor: [
                                'rgba(255, 99, 132,1)',
                                'rgba(255, 159, 64, 1)',
                                'rgba(255, 205, 86, 1)',
                                'rgba(75, 192, 192, 1)',
                                'rgba(54, 162, 235, 1)',
                                'rgba(153, 102, 255, 1)',
                                'rgba(201, 203, 207, 1)'
                            ],

                            borderWidth: 1
                        }]
                    },
                    options: {
                        scales: {
                            y: {
                                beginAtZero: true
                            }
                        }
                    }
                });

            })
            .catch(err => (
                console.log(err)
            ))

    </script>

{% endblock %}