account/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from .forms import CustomAuthenticationForm
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'account'


urlpatterns = [
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('signup/', views.register, name="signup"),
    # path('login/', LoginView.as_view(template_name='registration/login.html',
    #      form_class=CustomAuthenticationForm),  name='login')
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from ckeditor_uploader import views as ckeditor_views
from django.contrib.admin.views.decorators import staff_member_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls')),
    path('course/', include('course.urls')),
    path('accounts/', include('account.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('upload/', staff_member_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('__debug__/', include('debug_toolbar.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/urls.py
from django.urls import path
from . import views

from quiz import views as quiz_views

app_name = 'course'

urlpatterns = [

    path('', views.course_list_view, name='course_list'),

    path('categories/', views.course_home, name="course_home"),
    path('categories/<slug:slug>/', views.course_home, name="course_cat"),
    path('categories/<slug:parent_slug>/<slug:cat_slug>', views.user_course_list_view, name="course_category_list"),

    path('<slug:course_slug>/filter',
         views.course_list_view, name='course_filter'),
    path('create/', views.course_create_view, name='course_create'),
    path('detail/<slug:slug>/', views.course_detail_view, name='course_detail'),
    path('htmx/detail/<int:pk>/', views.course_include_detail_view, name='course_include_detail'),
    path('update/<int:pk>/', views.course_update_view, name='course_update'),
    path('active/<int:pk>', views.active_or_deactive_course, name='active_or_deactive_course'),
    path('delete/<int:pk>/', views.course_delete_view, name='course_delete'),

    # module
    path('module/<int:course_id>', views.module_form, name='module_create'),
    path('module/detail/<int:pk>', views.module_detail, name='module_detail'),
    path('module/<int:pk>/update', views.module_update_view, name="module_update"),
    path('module/<int:pk>/delete', views.module_delete_view, name="module_delete"),
    path('module/<int:module_id>/content/<model_name>/create', views.content_create_update_view,
         name="module_content_create"),
    path('module/<int:module_id>/content/<model_name>/<int:pk>/update', views.content_create_update_view,
         name="module_content_update"),
    path('module/<module_id>/<content_id>/detail/<item_id>/', views.content_detail_view, name='module_content_detail'),
    path('module/content/<int:pk>/delete', views.content_delete_view, name='module_content_delete'),

    # module quiz 
    path('module/<module_id>/create/quiz', views.module_create_quiz, name='module_quiz_create'),
    path('module/<module_id>/update/quiz/<quiz_id>', views.module_create_quiz, name='module_quiz_update'),
    path('module/<quiz_id>/detail/quiz/<module_id>', quiz_views.htmx_quiz_detail_view, name='module_quiz_detail'),

    # users paths

    path('user/detail/<int:pk>/', views.user_course_detail, name="user_course_detail"),
    path('user/courses', views.course_categories, name='user_course_list'),
    path('user/<slug:slug>', views.course_categories, name='user_course_categories'),
    path('user/module/detail/<int:pk>', views.module_detail_view, name='user_module_detail_view'),

    # fetch api

]

quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    # path('manage/'),
    path('testlar/', views.quiz_home, name="quiz_home"),
    path('test/<slug:slug>/', views.quiz_home, name="quiz_cat"),
    path('test/user/statistics', views.ResultApiView.as_view(), name='statistics_user'),
    path('test/<slug:slug>/<slug:quiz_slug>', views.user_quiz_list_view, name="user_quiz_list_view"),

    path('test/detail/<int:pk>/', views.user_quiz_detail, name="user_quiz_detail"),
    path('test/<int:pk>/start/', views.quiz_start, name="user_quiz_start"),
    path('test/<int:pk>/start/data', views.quiz_data_view, name="quiz_data"),
    path('test/<int:pk>/start/save', views.quiz_save, name="quiz_save"),
    path('test/<int:pk>/start/fetch', views.FetchApiView.as_view(), name="fetch"),
    # path('test/<int:pk>/save/', views.quiz_start, name="user_quiz_save"),

    path('test/create', views.quiz_create_view, name='quiz_create_view'),
    path('quiz_list/', views.quiz_list_view, name='quiz_list'),
    path('test/<int:pk>', views.quiz_detail_view, name='quiz_detail'),

    # htmx urls
    path('htmx/test/<int:pk>', views.htmx_quiz_detail_view, name='htmx_quiz_detail'),
    path('htmx/test/<int:pk>/delete', views.quiz_delete_view, name='quiz_delete'),
    path('htmx/test/<int:pk>/update', views.update_quiz, name='quiz_update'),
    path('htmx/test/<int:pk>/active', views.active_or_deactive, name='quiz_active_or_deactive'),
    path('htmx/create/question/<quiz_id>', views.question_form, name='create_question'),
    path('htmx/create/question/exel/<quiz_id>', views.export_question_excel, name='create_question_with_excel'),
    path('update/question/<question_id>', views.update_question, name='update_question'),
    path('delete/question/<question_id>', views.delete_question, name='delete_question'),

    # statistics user
    # manage
    path('manage/', views.manage_dashboard, name='manage_dashboard'),
    path('manage/statistics', views.statistics, name='manage_statistics'),
    path('manage/employers', views.employers, name='manage_employers'),
    path('manage/organization', views.organizations, name='manage_organizations'),
    path('api/manage/dashboard/info', views.quiz_dashboard_info, name='api_dashboard_info'),
    path('api/manage/statistics/org', views.statistics_org_api, name='statistics_org_api'),

]

quiz/views.py
import json
import uuid

import pytz
import redis, json
import vaex
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.conf import settings

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.base import TemplateResponseMixin, TemplateView, View
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.core.exceptions import ImproperlyConfigured
from django.db.models import Q, Count, Avg, Subquery, OuterRef, Sum
from braces.views import JsonRequestResponseMixin, CsrfExemptMixin
from django.db.models.functions import ExtractDay, ExtractYear

from django.contrib.auth.decorators import permission_required
from account.models import Organizations, CustomUser
from account.utils.recent_activity import RecentActivity
# models
from .models import Quiz, Question, Answer, Result, Category, ExcelFileUploaded
from .forms import QuestionForm, QuizForm, answer_formset, ExportExcelQuestion

from django.views.decorators.csrf import csrf_exempt

from datetime import datetime, date, timedelta, timezone
import requests
import pandas as pd
from uuid import uuid4

from django.views.decorators.cache import cache_page

r = redis.Redis(
    host=settings.REDIS_HOST,
    db=settings.REDIS_DB,
    port=settings.REDIS_PORT
)


# Create your views here.

class Dashboard(LoginRequiredMixin, TemplateView):
    template_name = 'quiz/dashboard.html'

    # @cache_page(60 * 15)
    def get(self, request):
        print('hello')
        if request.user.is_superuser or request.user.is_staff:
            return redirect('quiz:manage_dashboard')
        categories = Category.objects.filter(parent__isnull=True)[:7]
        end_date = datetime.today()
        st_date = end_date - timedelta(days=7)
        results = Result.objects.filter(user=request.user, quiz__module__isnull=True).select_related(
            'quiz__category__parent')

        return self.render_to_response({
            'object_list': categories,
            'results': results
        })


dashboard = Dashboard.as_view()


class QuizHomeView(LoginRequiredMixin, TemplateView):
    template_name = 'quiz/quiz_home.html'

    # @cache_page(60 * 15)
    def get(self, request, slug=None, *args, **kwargs):

        if slug is not None:
            today = datetime.now(pytz.timezone('Asia/Tashkent'))
            quiz = Quiz.objects.filter(category_id=OuterRef('pk'), period_date__isnull=False, period_date__gte=today,
                                       module__isnull=True)

            categories = Category.objects.filter(parent__slug=slug).annotate(quiz=Subquery(quiz.values('id')[:1]), )


        else:
            categories = Category.objects.filter(level=0).order_by('name').distinct('name').values('name',
                                                                                                   'level',
                                                                                                   'icon',
                                                                                                   'quizs',
                                                                                                   'slug',
                                                                                                   'children')

        return self.render_to_response({
            'object_list': categories,
        })

        # if slug is not None:
        #     categories = Category.objects.prefetch_related('quizs').filter(parent__slug=slug)
        # else:
        #     categories = Category.objects.all()
        #
        # return self.render_to_response({
        #     'object_list': categories,
        #     # 'cat': cat
        # })


quiz_home = QuizHomeView.as_view()


class UserQuizListView(LoginRequiredMixin, ListView):
    model = Quiz
    template_name = 'quiz/user_quiz_list.html'

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        queryset = queryset.filter(active=True, period_date__gte=datetime.now(tz=pytz.timezone('Asia/Tashkent')),
                                   category__slug=self.kwargs['quiz_slug'])
        return queryset


user_quiz_list_view = UserQuizListView.as_view()


class UserQuizDetail(LoginRequiredMixin, DetailView):
    model = Quiz
    template_name = 'quiz/detail.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        try:
            result = get_object_or_404(Result, user=self.request.user, quiz=self.object)
        except:
            result = None
        resent = RecentActivity(self.request.user)
        if self.object.course:
            title = f"{self.object.category}-{self.object.course}"
        else:
            title = f"{self.object.category}"
        data = {
            'date': datetime.now().timestamp(),
            'category': 'test',
            'title': title,
            'url': self.request.path
        }
        resent.add_resent_activity(data)

        context['result'] = result
        return context


user_quiz_detail = UserQuizDetail.as_view()


class QuizStart(LoginRequiredMixin, TemplateView):
    template_name = 'quiz/quiz_start.html'

    def get(self, request, pk):
        request.session['user'] = f"{datetime.now()}"
        quiz = get_object_or_404(Quiz, pk=pk)
        result = Result.objects.filter(quiz=quiz)
        # if result[0].attempts > 3:
        #     return redirect('/')
        return self.render_to_response({
            'quiz': quiz
        })

    def post(self, request, pk):
        quiz = get_object_or_404(Quiz, pk=pk)
        questions = None
        return HttpResponse(request.POST)
        # return self.render_to_response({
        #     'data': questions,
        #     'time': 10,
        # })


quiz_start = QuizStart.as_view()


def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []

    try:
        result = Result.objects.get(user=request.user)
        if result:
            return redirect(reverse('quiz:user_quiz_detail'))
    except:
        for q in quiz.get_questions():
            answers = []
            for a in q.get_answers():
                ans = {
                    'text': a.text,
                    'uuid': a.uuid,
                    'q_uid': q.uuid
                }
                answers.append(ans)
            questions.append({str(q): answers})
        return JsonResponse({
            'data': questions,
            'time': quiz.time,
        })


class SaveQuiz(LoginRequiredMixin, JsonRequestResponseMixin, View):

    def post(self, request, pk):
        quiz = Quiz.objects.get(pk=pk)
        print("quiz.title")
        item = self.request_json

        # print(item)
        score = 0
        wrong = 0
        # questions = item['data'].items()
        count = 0
        for x, y in item['data'].items():
            question = Question.objects.get(uuid=x)
            count += 1
            # question = Question.objects.get(uuid=x)
            if y is not None:
                ans = Answer.objects.get(uuid=y)
                if ans.correct:
                    score += 1
                else:
                    wrong += 1

        multipler = 100 / count
        result = score * multipler

        try:
            obj = Result.objects.get(quiz=quiz, user=request.user)
            obj.attempts += 1
            obj.score = round(result)
            obj.save()
        except:
            obj = Result.objects.create(
                quiz=quiz, user=request.user, score=result, attempts=1
            )
            obj.save()

        return self.render_json_response({
            'quiz': str(quiz.category),
            'correct': score,
            'count': count,
            'score': result,
            'not_check': count - score,
            'wrong': wrong
        })


quiz_save = SaveQuiz.as_view()


class FetchApiView(LoginRequiredMixin, JsonRequestResponseMixin, View):

    def post(self, request, pk):
        item = self.request_json

        print(item)

        return self.render_json_response({
            'quiz': 'data send'
        })


# manage views

class ManageDashboard(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/manage/dashboard.html'

    def get(self, request):
        result = Result.objects.filter(quiz__module__isnull=True)
        year = result.filter(date__year=datetime.today().strftime('%Y')).count()
        month = result.filter(date__month=datetime.today().strftime('%m')).count()
        day = result.filter(date__day=datetime.today().strftime('%d')).count()
        organizations = Organizations.objects.all()
        print(datetime.today())
        return self.render_to_response({
            'year': year,
            'month': month,
            'day': day,
            'organizations': organizations
        })


manage_dashboard = ManageDashboard.as_view()


class QuizCreateView(LoginRequiredMixin, CreateView):
    model = Quiz
    template_name = 'dashboard/manage/create_quiz.html'
    fields = ['title', 'category', 'number_of_questions', 'score_to_pass', 'time']

    def form_valid(self, form):
        self.object = form.save()
        return redirect('quiz:quiz_detail', pk=self.object.id)


quiz_create_view = QuizCreateView.as_view()


class QuizUpdateView(UpdateView):
    model = Quiz
    fields = ['category', 'number_of_questions', 'score_to_pass', 'time']
    template_name = 'dashboard/manage/quiz_form.html'
    pk_url_kwarg = 'pk'

    # @csrf_exempt
    # def dispatch(self, request, *args, **kwargs):
    #     print('hello world')
    #     return super().dispatch(request, *args, **kwargs)

quiz/templates/dashboard/include/__aside.html
{% url 'quiz:manage_dashboard' as dashboard %}
{% url 'quiz:manage_statistics' as statistics %}
{% url 'quiz:quiz_list' as quiz_list %}
{% url 'quiz:quiz_create_view' as quiz_create_view %}
{% url 'course:course_list' as course_list %}
{% url 'course:course_create' as course_create %}
{% url 'quiz:manage_employers' as manage_employers %}
{% url 'quiz:manage_organizations' as manage_organizations %}
{% with request.path as path %}

    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">


                <a
                        {% if path == dashboard %}
                            class="nav-link"
                        {% else %}
                            class="nav-link collapsed"
                        {% endif %}
                            class="nav-link" href="{% url 'quiz:manage_dashboard' %}">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li><!-- End Dashboard Nav -->

            <li class="nav-item">
                <a
                        {% if path == statistics %}
                            class="nav-link"
                        {% else %}
                            class="nav-link collapsed"
                        {% endif %}
                            href="{% url 'quiz:manage_statistics' %}">
                    <i class="bi bi-graph-up-arrow"></i>
                    <span>Статистика</span>

                </a>
            </li><!-- End Profile Page Nav -->

            <li class="nav-item">
                <a
                        {% if path == quiz_list or path == quiz_create_view %}
                            class="nav-link"
                        {% else %}
                            class="nav-link collapsed"
                        {% endif %}
                         data-bs-target="#quiz-nav" aria-expanded="true" data-bs-toggle="collapse"
                   href="#">
                    <i class="bi bi-journal-text"></i><span>Test</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="quiz-nav" class="nav-content collapse show " data-bs-parent="#sidebar-nav">
                    <li>
                        <a
                                {% if path == quiz_list %}
                                    class="active"
                                {% endif %}
                                href="{% url 'quiz:quiz_list' %}">
                            <i class="bi bi-circle"></i><span>Testlar</span>
                        </a>
                    </li>

                    <li>
                        <a
                                {% if path == quiz_create_view %}
                                    class="active"
                                {% endif %}
                                href="{% url 'quiz:quiz_create_view' %}">
                            <i class="bi bi-circle"></i><span>Test Yaratish</span>
                        </a>
                    </li>


                </ul>
            </li><!-- End Forms Nav -->


            <li class="nav-item">
                <a
                        {% if path == course_list or path == course_create %}
                            class="nav-link"
                        {% else %}
                            class="nav-link collapsed"
                        {% endif %}
                            class="nav-link collapsed" data-bs-target="#course-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-journal-text"></i><span>Course</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="course-nav" class="nav-content collapse show" data-bs-parent="#sidebar-nav">
                    <li>


                        <a
                                {% if path == course_list %}
                                    class="active"
                                {% endif %}
                                    href="{% url 'course:course_list' %}">
                            <i class="bi bi-circle"></i><span>Kurslar</span>
                        </a>
                    </li>

                    <li>
                        <a
                                {% if path == course_create %}
                                    class="active"
                                {% endif %}
                                href="{% url 'course:course_create' %}">
                            <i class="bi bi-circle"></i><span>Kurs Yaratish</span>
                        </a>
                    </li>


                </ul>
            </li><!-- End Forms Nav -->


            <li class="nav-item">
                <a
                        {% if path == manage_employers %}
                            class="nav-link"
                        {% else %}
                            class="nav-link collapsed"
                        {% endif %}
                         href="{% url 'quiz:manage_employers' %}">
                    <i class="bi bi-people-fill"></i>
                    <span>Ходимлар</span>
                </a>
            </li><!-- End Profile Page Nav -->

            <li class="nav-item">
                <a
                        {% if path == manage_organizations %}
                            class="nav-link"
                        {% else %}
                            class="nav-link collapsed"
                        {% endif %}
                         href="{% url 'quiz:manage_organizations' %}">
                    <i class="bi bi-building"></i>
                    <span>Бўлимлар</span>
                </a>
            </li><!-- End Profile Page Nav -->


        </ul>

    </aside><!-- End Sidebar-->

{% endwith %}

quiz/templates/dashboard/include/__footer.html
<footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </footer><!-- End Footer -->

quiz/templates/dashboard/include/__sidebar.html
{% load static %}
{% load timesince %}
<div class="sidebar-dashboard section dashboard">

    <div class="actions__sidebar-dashboard">
        <div class="filter">
            <a class="icon" href="#" data-bs-toggle="dropdown"> <img src="{% static 'assets/img/setting.png' %}"
                                                                     width="25" alt="setting icon"/></a>
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">

                {#                        <li><a class="dropdown-item" href="#">Today</a></li>#}
                {#                        <li><a class="dropdown-item" href="#">This Month</a></li>#}
                <li><a class="dropdown-item" href="{% url 'account:logout' %}">Chiqish</a></li>
            </ul>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Oxirgi faoliyat</h5>


            <div class="activity">
                {% for datum in data %}
                    <div class="activity-item">
                        <div class="activite-label">
                            {{ datum.date|time_since }}
                        </div>
                        <i class='bi bi-circle-fill activity-badge text-success align-self-start'></i>
                        <div class="activity-content">
                            <span class="text-bg-danger"></span>
                            <a href="{{ datum.url }}" class="fw-bold text-dark">{{ datum.title }}
                                ({{ datum.category }})</a>

                        </div>
                    </div><!-- End activity item-->
                {% endfor %}


                {##}
                {#                        <div class="activity-item d-flex">#}
                {#                            <div class="activite-label">56 min</div>#}
                {#                            <i class='bi bi-circle-fill activity-badge text-danger align-self-start'></i>#}
                {#                            <div class="activity-content">#}
                {#                                Voluptatem blanditiis blanditiis eveniet#}
                {#                            </div>#}
                {#                        </div><!-- End activity item-->#}
                {##}
                {#                        <div class="activity-item d-flex">#}
                {#                            <div class="activite-label">2 hrs</div>#}
                {#                            <i class='bi bi-circle-fill activity-badge text-primary align-self-start'></i>#}
                {#                            <div class="activity-content">#}
                {#                                Voluptates corrupti molestias voluptatem#}
                {#                            </div>#}
                {#                        </div><!-- End activity item-->#}
                {##}
                {#                        <div class="activity-item d-flex">#}
                {#                            <div class="activite-label">1 day</div>#}
                {#                            <i class='bi bi-circle-fill activity-badge text-info align-self-start'></i>#}
                {#                            <div class="activity-content">#}
                {#                                Tempore autem saepe <a href="#" class="fw-bold text-dark">occaecati voluptatem</a>#}
                {#                                tempore#}
                {#                            </div>#}
                {#                        </div><!-- End activity item-->#}
                {##}
                {#                        <div class="activity-item d-flex">#}
                {#                            <div class="activite-label">2 days</div>#}
                {#                            <i class='bi bi-circle-fill activity-badge text-warning align-self-start'></i>#}
                {#                            <div class="activity-content">#}
                {#                                Est sit eum reiciendis exercitationem#}
                {#                            </div>#}
                {#                        </div><!-- End activity item-->#}
                {##}
                {#                        <div class="activity-item d-flex">#}
                {#                            <div class="activite-label">4 weeks</div>#}
                {#                            <i class='bi bi-circle-fill activity-badge text-muted align-self-start'></i>#}
                {#                            <div class="activity-content">#}
                {#                                Dicta dolorem harum nulla eius. Ut quidem quidem sit quas#}
                {#                            </div>#}
                {#                        </div><!-- End activity item-->#}
                {#                        <div class="activity-item d-flex">#}
                {#                            <div class="activite-label">4 weeks</div>#}
                {#                            <i class='bi bi-circle-fill activity-badge text-muted align-self-start'></i>#}
                {#                            <div class="activity-content">#}
                {#                                Dicta dolorem harum nulla eius. Ut quidem quidem sit quas#}
                {#                            </div>#}
                {#                        </div><!-- End activity item-->#}
                {#                        <div class="activity-item d-flex">#}
                {#                            <div class="activite-label">4 weeks</div>#}
                {#                            <i class='bi bi-circle-fill activity-badge text-muted align-self-start'></i>#}
                {#                            <div class="activity-content">#}
                {#                                Dicta dolorem harum nulla eius. Ut quidem quidem sit quas#}
                {#                            </div>#}
                {#                        </div><!-- End activity item-->#}
                {#                        <div class="activity-item d-flex">#}
                {#                            <div class="activite-label">4 weeks</div>#}
                {#                            <i class='bi bi-circle-fill activity-badge text-muted align-self-start'></i>#}
                {#                            <div class="activity-content">#}
                {#                                Dicta dolorem harum nulla eius. Ut quidem quidem sit quas#}
                {#                            </div>#}
                {#                        </div><!-- End activity item-->#}
                {#                        <div class="activity-item d-flex">#}
                {#                            <div class="activite-label">4 weeks</div>#}
                {#                            <i class='bi bi-circle-fill activity-badge text-muted align-self-start'></i>#}
                {#                            <div class="activity-content">#}
                {#                                Dicta dolorem harum nulla eius. Ut quidem quidem sit quas#}
                {#                            </div>#}
                {#                        </div><!-- End activity item-->#}
                {#                        <div class="activity-item d-flex">#}
                {#                            <div class="activite-label">4 weeks</div>#}
                {#                            <i class='bi bi-circle-fill activity-badge text-muted align-self-start'></i>#}
                {#                            <div class="activity-content">#}
                {#                                Dicta dolorem harum nulla eius. Ut quidem quidem sit quas#}
                {#                            </div>#}
                {#                        </div><!-- End activity item-->#}

            </div>

        </div>
    </div><!-- End Recent Activity -->


    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Тестни Узлаштириш коефисенти</h5>

            <!-- Bar Chart -->
            <canvas id="barChart" style="max-height: 400px;"></canvas>

            <!-- End Bar CHart -->

        </div>
    </div>
</div>