config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from ckeditor_uploader import views as ckeditor_views
from django.contrib.admin.views.decorators import staff_member_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls')),
    path('course/', include('course.urls')),
    path('accounts/', include('account.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('upload/', staff_member_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('__debug__/', include('debug_toolbar.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/urls.py
from django.urls import path
from . import views

from quiz import views as quiz_views

app_name = 'course'

urlpatterns = [

    path('', views.course_list_view, name='course_list'),

    path('categories/', views.course_home, name="course_home"),
    path('categories/<slug:slug>/', views.course_home, name="course_cat"),
    path('categories/<slug:parent_slug>/<slug:cat_slug>', views.user_course_list_view, name="course_category_list"),

    path('<slug:course_slug>/filter',
         views.course_list_view, name='course_filter'),
    path('create/', views.course_create_view, name='course_create'),
    path('detail/<slug:slug>/', views.course_detail_view, name='course_detail'),
    path('htmx/detail/<int:pk>/', views.course_include_detail_view, name='course_include_detail'),
    path('update/<int:pk>/', views.course_update_view, name='course_update'),
    path('active/<int:pk>', views.active_or_deactive_course, name='active_or_deactive_course'),
    path('delete/<int:pk>/', views.course_delete_view, name='course_delete'),

    # module
    path('module/<int:course_id>', views.module_form, name='module_create'),
    path('module/detail/<int:pk>', views.module_detail, name='module_detail'),
    path('module/<int:pk>/update', views.module_update_view, name="module_update"),
    path('module/<int:pk>/delete', views.module_delete_view, name="module_delete"),
    path('module/<int:module_id>/content/<model_name>/create', views.content_create_update_view,
         name="module_content_create"),
    path('module/<int:module_id>/content/<model_name>/<int:pk>/update', views.content_create_update_view,
         name="module_content_update"),
    path('module/<module_id>/<content_id>/detail/<item_id>/', views.content_detail_view, name='module_content_detail'),
    path('module/content/<int:pk>/delete', views.content_delete_view, name='module_content_delete'),

    # module quiz 
    path('module/<module_id>/create/quiz', views.module_create_quiz, name='module_quiz_create'),
    path('module/<module_id>/update/quiz/<quiz_id>', views.module_create_quiz, name='module_quiz_update'),
    path('module/<quiz_id>/detail/quiz/<module_id>', quiz_views.htmx_quiz_detail_view, name='module_quiz_detail'),

    # users paths

    path('user/detail/<int:pk>/', views.user_course_detail, name="user_course_detail"),
    path('user/courses', views.course_categories, name='user_course_list'),
    path('user/<slug:slug>', views.course_categories, name='user_course_categories'),
    path('user/module/detail/<int:pk>', views.module_detail_view, name='user_module_detail_view'),

    # fetch api

]

quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    # path('manage/'),
    path('testlar/', views.quiz_home, name="quiz_home"),
    path('test/<slug:slug>/', views.quiz_home, name="quiz_cat"),
    path('test/user/statistics', views.ResultApiView.as_view(), name='statistics_user'),
    path('test/<slug:slug>/<slug:quiz_slug>', views.user_quiz_list_view, name="user_quiz_list_view"),

    path('test/detail/<int:pk>/', views.user_quiz_detail, name="user_quiz_detail"),
    path('test/<int:pk>/start/', views.quiz_start, name="user_quiz_start"),
    path('test/<int:pk>/start/data', views.quiz_data_view, name="quiz_data"),
    path('test/<int:pk>/start/save', views.quiz_save, name="quiz_save"),
    path('test/<int:pk>/start/fetch', views.FetchApiView.as_view(), name="fetch"),
    # path('test/<int:pk>/save/', views.quiz_start, name="user_quiz_save"),

    path('test/create', views.quiz_create_view, name='quiz_create_view'),
    path('quiz_list/', views.quiz_list_view, name='quiz_list'),
    path('test/<int:pk>', views.quiz_detail_view, name='quiz_detail'),

    # htmx urls
    path('htmx/test/<int:pk>', views.htmx_quiz_detail_view, name='htmx_quiz_detail'),
    path('htmx/test/<int:pk>/delete', views.quiz_delete_view, name='quiz_delete'),
    path('htmx/test/<int:pk>/update', views.update_quiz, name='quiz_update'),
    path('htmx/test/<int:pk>/active', views.active_or_deactive, name='quiz_active_or_deactive'),
    path('htmx/create/question/<quiz_id>', views.question_form, name='create_question'),
    path('htmx/create/question/exel/<quiz_id>', views.export_question_excel, name='create_question_with_excel'),
    path('update/question/<question_id>', views.update_question, name='update_question'),
    path('delete/question/<question_id>', views.delete_question, name='delete_question'),

    # statistics user
    # manage
    path('manage/', views.manage_dashboard, name='manage_dashboard'),
    path('manage/statistics', views.statistics, name='manage_statistics'),
    path('manage/employers', views.employers, name='manage_employers'),
    path('manage/organization', views.organizations, name='manage_organizations'),
    path('api/manage/dashboard/info', views.quiz_dashboard_info, name='api_dashboard_info'),
    path('api/manage/statistics/org', views.statistics_org_api, name='statistics_org_api'),

]

course/forms.py
from django import forms
from .models import Course, Category, Module
from quiz.models import Quiz
from mptt.forms import TreeNodeChoiceField
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify


class CourseForm(forms.ModelForm):
    subject = TreeNodeChoiceField(label=_("Bo'lim"),queryset=Category.objects.all())
    title = forms.CharField(label=_("Kurs nomi"))

    class Meta:
        model = Course
        fields = ['subject', 'title', 'active']

    # def save(self, commit=True):
    #     instance = super().save(commit=False)
    #     cd = self.cleaned_data
    #     title = cd['title']
    #     instance.slug = slugify(title)
    #     return instance


class ModuleForm(forms.ModelForm):
    course = forms.ModelChoiceField(
        queryset=Course.objects.all(), widget=forms.HiddenInput)
    title = forms.CharField(label=_("Mavzu Nomi"))
    parent = forms.ModelChoiceField(queryset=Module.objects.filter(parent__isnull=True), required=False)

    class Meta:
        model = Module
        fields = ['course', 'title', 'parent']

    def __init__(self, course=None, *args, **kwargs):
        super(ModuleForm, self).__init__(*args, **kwargs)
        if course:
            self.fields['parent'].queryset = Module.objects.filter(course=course, parent__isnull=True)


class ModuleQuizForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(), widget=forms.HiddenInput)
    course = forms.ModelChoiceField(
        queryset=Course.objects.all(), widget=forms.HiddenInput)
    module = forms.ModelChoiceField(
        queryset=Module.objects.all(), widget=forms.HiddenInput)

    class Meta:
        model = Quiz
        fields = ['category', 'course', 'module',
                  'number_of_questions', 'score_to_pass', 'time']

course/views.py
import json
import urllib

import pytz
import redis
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django.conf import settings
from django.contrib.auth.decorators import permission_required
from django.db.models import F, OuterRef, Count, Q, Avg
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.base import TemplateResponseMixin, View, TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib import messages

from account.utils.recent_activity import RecentActivity
from .models import Course, Category, Module, Content, Text
from .forms import CourseForm, ModuleForm, ModuleQuizForm
from quiz.models import Question, Quiz, Result, Answer

from django.forms.models import modelform_factory
from django.apps import apps

from braces.views import CsrfExemptMixin, JsonRequestResponseMixin
from ckeditor.widgets import CKEditorWidget
from django.utils.text import slugify
from datetime import datetime

r = redis.Redis(
    host=settings.REDIS_HOST,
    db=settings.REDIS_DB,
    port=settings.REDIS_PORT
)

r.keys()


class CourseHomeView(LoginRequiredMixin, TemplateView):
    template_name = 'course/course_home.html'

    def get(self, request, slug=None, *args, **kwargs):
        categories = Category.objects.all()
        quiz = None
        if slug is not None:
            cat = Category.objects.get(slug=slug)
            categories = cat.get_children()

        return self.render_to_response({
            'object_list': categories,
            'quiz': quiz
        })


course_home = CourseHomeView.as_view()


class CourseListView(LoginRequiredMixin, TemplateResponseMixin, View):
    template_name = 'course/dashboard/course_list.html'

    # def get(self, request, slug=None, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     if slug is not None:
    #         context['object_list'] = self.get_queryset().filter(
    #             subject__slug=slug)

    #     return self.render_to_response(context)

    def get(self, request):
        object_list = Course.objects.select_related('subject', 'subject__parent').prefetch_related('modules')
        return self.render_to_response({
            'object_list': object_list
        })

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['object_list'] = Course.objects.filter(
                subject__slug=kwargs['slug'])
        except:
            pass

        return context


course_list_view = CourseListView.as_view()


class CourseDetailView(DetailView):
    model = Course
    template_name = 'course/dashboard/manage/course_detail.html'
    slug_url_kwarg = 'slug'

    def get_queryset(self):
        return super().get_queryset().select_related('subject')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.object = self.get_object()
        modules = Module.objects.filter(course=self.object).select_related('parent')
        context['modules'] = modules
        return context


course_detail_view = CourseDetailView.as_view()


class CourseCreateView(LoginRequiredMixin, CreateView):
    model = Course
    template_name = 'course/dashboard/manage/course_create.html'
    form_class = CourseForm
    success_url = reverse_lazy('course:course_list')

    def form_valid(self, form):
        form.instance.slug = slugify(form.cleaned_data['title'])
        return super().form_valid(form)


course_create_view = CourseCreateView.as_view()


class CourseUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    permission_required = 'course.view_course'
    model = Course
    template_name = 'course/dashboard/manage/course_form.html'
    fields = ['subject', 'title', 'active']

    def form_valid(self, form):
        self.object = form.save()
        context = {
            'object': self.object
        }
        return render(self.request, 'course/dashboard/manage/include_course_detail.html', context)


course_update_view = CourseUpdateView.as_view()


class CourseIncludeDetail(PermissionRequiredMixin, LoginRequiredMixin, DetailView):
    permission_required = 'course.view_course'
    model = Course
    template_name = 'course/dashboard/manage/include_course_detail.html'


course_include_detail_view = CourseIncludeDetail.as_view()


@permission_required('course.view_course')
def active_or_deactive_course(request, pk):
    object = get_object_or_404(Course, pk=pk)
    if object.active:
        object.active = False
        object.save()
    else:
        object.active = True
        object.save()
    return render(request, 'course/dashboard/manage/active_or_deactive_course.html', context={'object': object})


class CourseDeleteView(LoginRequiredMixin, DeleteView):
    model = Course
    template_name = 'course/dashboard/manage/course_delete.html'
    success_url = reverse_lazy('course:course_list')


course_delete_view = CourseDeleteView.as_view()


class ModuleCreateUpdateView(LoginRequiredMixin, TemplateResponseMixin, View):
    template_name = 'course/dashboard/manage/module_form.html'

    def get(self, request, course_id=None, module_id=None, *args, **kwargs):
        course = get_object_or_404(Course, pk=course_id)
        if module_id is not None:
            module = get_object_or_404(Module, pk=module_id)
            form = ModuleForm(instance=module)
            return self.render_to_response(
                {'form': form,
                 'course': course
                 }
            )
        else:
            form = ModuleForm(initial={'course': course}, course=course)
            return self.render_to_response(
                {'form': form,
                 'course': course
                 }
            )

    def post(self, request, course_id=None, module_id=None):
        course = get_object_or_404(Course, pk=course_id)
        form = ModuleForm(data=request.POST)
        if form.is_valid():
            obj = form.save()
            return HttpResponseRedirect(reverse('course:course_detail', kwargs={'slug': course.slug}))


module_form = ModuleCreateUpdateView.as_view()


class ModuleUpdateView(LoginRequiredMixin, UpdateView):
    model = Module
    form_class = ModuleForm
    template_name = 'course/dashboard/manage/module_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        self.object = self.get_object()
        context['course'] = self.object.course
        return context

    def get_success_url(self):
        print(self.object)
        return reverse('course:course_detail', kwargs={'slug': (self.object.course.slug)})


module_update_view = ModuleUpdateView.as_view()


class ModuleDeleteView(LoginRequiredMixin, DeleteView):
    model = Module
    template_name = 'course/dashboard/manage/module_delete.html'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.course = self.object.course
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        print(self.course.slug)
        return reverse('course:course_detail', args=(self.course.slug,))


module_delete_view = ModuleDeleteView.as_view()


class ModuleDetailView(LoginRequiredMixin, TemplateView):
    # model = Module
    template_name = 'course/dashboard/pages/detail_module.html'

    def get(self, request, pk):
        module = get_object_or_404(Module, pk=pk)
        modules = Module.objects.select_related('parent', 'course').filter(course=module.course)

        return self.render_to_response({
            "object": module,
            'modules': modules
        })

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data()
    #     object = self.get_object()
    #     context['modules'] = Module.objects.prefetch_related('contents__content_type').select_related('course', 'parent').filter(course=object.course)
    #     return context


module_detail = ModuleDetailView.as_view()


class ContentCreateUpdateView(LoginRequiredMixin, TemplateResponseMixin, View):
    module = None
    model = None
    obj = None
    template_name = 'course/dashboard/manage/content/content-form.html'

    def get_model(self, model_name):
        if model_name in ['video', 'text', 'image', 'file']:
            return apps.get_model(app_label='course', model_name=model_name)

    def get_form(self, model, *args, **kwrags):
        if model is Text:
            Form = modelform_factory(model, exclude=[
                'created',
                'updated',
                'order',
                # 'title'
            ], widgets={'content': CKEditorUploadingWidget()})
        else:
            Form = modelform_factory(model, exclude=[
                'created',
                'updated',
                'order'
            ])

        return Form(*args, **kwrags)

    def dispatch(self, request, module_id, model_name, pk=None, *args, **kwargs):
        self.module = get_object_or_404(Module, pk=module_id)
        self.model = self.get_model(model_name)
        print(request.method, pk)
        if pk:
            self.obj = get_object_or_404(self.model, id=pk)
        return super().dispatch(request, module_id, model_name, pk, *args, **kwargs)

    def get(self, request, module_id, model_name, id=None):
        form = self.get_form(self.model, instance=self.obj)
        return self.render_to_response({'form': form,
                                        'object': self.obj,
                                        'modul_id': module_id,

course/templates/course/users/pages/course_categories.html
{% extends 'user/base.html' %}
{% load static %}
{% load mptt_tags %}

{% block style %}
    <link rel="stylesheet" href="{% static 'user/dash/css/style.css' %}">
{% endblock %}
{% block title %}
    Homepage
{% endblock %}

{% block content %}
    <div class="wrapper-dashboard bg-light">
        <div class="main-dashboard">
            <div class="top__main-dashboard ">
                <div class="profile-group__main-dashboard rounded-3">
                    <img
                            class="rounded-circle border border-4"
                            src="{{ photo }}"
                            alt="profile"
                            width="130"
                            height="130"
                    />
                    {#                    <h5 class="title__profile-group fw-bold mb-0 mt-1">Ali Barin</h5>#}
                    <p class="text__profile-group text-secondary p-2"
                       style="text-align: center">{{ organization.name }}</p>
                    <p class="text__profile-group text-secondary " style="text-align: center">{{ staff_full }}</p>
                </div>
                <div class="search-group__main-dashboard rounded-3">
                    <h3 class="text-light fw-bolder">{{ fullname }}</h3>
                    <div class="form-group search-content">
              <span class="google-icon__search-content">

              </span>
                        <input
                                type="text"
                                class="form-control bg-white bg-opacity-75 rounded-5"
                                placeholder="Поиск"
                        />
                        {#                        <div class="search-icon__search-content">#}
                        {#                            <img#}
                        {#                                    src="./assets/search-icon.png"#}
                        {#                                    alt="search icon"#}
                        {#                                    width="30"#}
                        {#                            />#}
                        {#                        </div>#}
                    </div>
                </div>
            </div>
            <div class="middle__main-dashboard">
                <h3 class="title-dashboard">Билим ошириш бўлими</h3>
                <hr>

                <div class="content__middle-dashboard">
                    <div class="links-group__main-dashboard">

                        {% for object in object_list %}
                            {% if object.courses %}

                                <a href="{% url 'course:user_course_detail' object.courses %}"
                                   class="link-card__main-dashboard rounded-3">
                                    <span class="badge rounded-pill bg-success align-self-end">course</span>

                                    {% if object.icon %}
                                        <img width="70" src="{% get_media_prefix %}{{ object.icon }}"
                                             alt="{{ object.icon }}"/>
                                    {% else %}
                                        <img width="70" src="{% static 'user/dash/img/file.png' %}" alt="icon"/>

                                    {% endif %}
                                    <p class="text-secondary">{{ object.name }}</p>
                                </a>
                            {% elif object.children %}
                                <a href="{% url 'course:user_course_categories' object.slug %}"
                                   class="link-card__main-dashboard rounded-3">

                                    {% if object.icon %}
                                        <img width="70" src="{% get_media_prefix %}{{ object.icon }}"
                                             alt="{{ object.icon }}"/>
                                    {% else %}
                                        <img width="70" src="{% static 'user/dash/img/file.png' %}" alt="icon"/>

                                    {% endif %}

                                    <p class="text-secondary">{{ object.name }}</p>
                                </a>
                            {% else %}
                                <a
                                        class="link-card__main-dashboard rounded-3">

                                    {% if object.icon %}
                                        <img width="70" src="{% get_media_prefix %}{{ object.icon }}"
                                             alt="{{ object.icon }}"/>
                                    {% else %}
                                        <img width="70" src="{% static 'user/dash/img/file.png' %}" alt="icon"/>

                                    {% endif %}

                                    <p class="text-secondary">{{ object.name }}</p>
                                </a>
                            {% endif %}

                        {% endfor %}


                        {#                        {% recursetree object_list %}#}
                        {#                            {% if not node.is_child_node %}#}
                        {#                                <a href="{% url 'course:user_course_categories' node.slug %}"#}
                        {#                                   class="link-card__main-dashboard rounded-3">#}
                        {##}
                        {#                                    {% if node.icon %}#}
                        {#                                        <img width="70" src="{{ node.icon.url }}" alt="icon"/>#}
                        {#                                    {% else %}#}
                        {#                                        <img width="70" src="{% static 'user/dash/img/file.png' %}" alt="icon"/>#}
                        {##}
                        {#                                    {% endif %}#}
                        {#                                    <p class="text-secondary">{{ node }}</p>#}
                        {#                                </a>#}
                        {#                            {% else %}#}
                        {#                                {% with node.cat_course.first as course %}#}
                        {#                                    {% if course %}#}
                        {#                                        <a href="{% url 'course:user_course_detail' course.pk %}"#}
                        {#                                           class="link-card__main-dashboard rounded-3">#}
                        {#                                            <span class="badge rounded-pill bg-success align-self-end">course</span>#}
                        {#                                            {% if node.icon %}#}
                        {#                                                <img width="70" src="{{ node.icon.url }}" alt="icon"/>#}
                        {#                                            {% else %}#}
                        {#                                                <img width="70" src="{% static 'user/dash/img/file.png' %}"#}
                        {#                                                     alt="icon"/>#}
                        {##}
                        {#                                            {% endif %}#}
                        {#                                            <p class="text-secondary">{{ node }}</p>#}
                        {#                                        </a>#}
                        {#                                    {% else %}#}
                        {#                                        <div href="{% url 'course:course_cat' node.slug %}"#}
                        {#                                             class="link-card__main-dashboard rounded-3">#}
                        {#                                            {% if node.icon %}#}
                        {#                                                <img width="70" src="{{ node.icon.url }}" alt="icon"/>#}
                        {#                                            {% else %}#}
                        {#                                                <img width="70" src="{% static 'user/dash/img/file.png' %}"#}
                        {#                                                     alt="icon"/>#}
                        {#                                            {% endif %}#}
                        {#                                            <p class="text-secondary">{{ node }}</p>#}
                        {#                                        </div>#}
                        {#                                    {% endif %}#}
                        {#                                {% endwith %}#}
                        {#                            {% endif %}#}
                        {#                        {% endrecursetree %}#}


                    </div>
                    {#                    {% for object in object_list %}#}
                    {#                        {{ object }}~ {{ object.level }}<br><br>#}
                    {#                    {% endfor %}#}


                </div>
            </div>
            {% if results %}
                <div class="bottom__main-dashboard">
                    <h3 class="title-dashboard">Natijalar</h3>
                    <div class="table-responsive">
                        <table class="table align-middle mb-0 bg-none borderless">
                            <thead class="bg-light">
                            <tr>
                                <th>Yo'nalish</th>
                                <th>Sana</th>
                                <th>Natija</th>
                                <th>Urunishlar soni</th>
                                {#                                <th>Status</th>#}
                            </tr>
                            </thead>
                            <tbody>
                            {% for result in results %}
                                <tr
                                        style="
                                    box-shadow: rgba(100, 100, 111, 0.2) 2px 3px 5px 0px;
                                    background: white;
                                "
                                >
                                    <td>
                                        <p class="fw-bold">
                                            <a href="#">{{ result.course.category.parent }}</a></p>
                                    </td>
                                    <td>
                                        <p class="fw-bold">{{ result.date }}</p>
                                    </td>
                                    <td>
                                        <p class="fw-bold">{{ result.score|floatformat:0 }}%</p>

                                    </td>
                                    <td>
                                        <p class="fw-bold">{{ result.attempts }}</p>
                                    </td>
                                    <td>
                                        {#                                        <span class="badge rounded-pill bg-warning">Completed</span>#}
                                    </td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            {% endif %}

        </div>
        {% include 'dashboard/include/__sidebar.html' %}
    </div>
{% endblock %}

{% block include_js %}
    <script>
        const url = '{% url 'quiz:statistics_user' %}'
        var options = {
            method: 'GET',
            mode: 'same-origin',
            headers: {
                "Content-Type": "application/json",

            }
        }
        fetch(url, options)
            .then(response => response.json())
            .then(data => {
                new Chart(document.querySelector('#barChart'), {
                    type: 'bar',
                    data: {
                        labels: data.labels,
                        datasets: [{
                            label: "O'zlashtirish",
                            data: data.data,
                            backgroundColor: [
                                'rgba(255, 99, 132,1)',
                                'rgba(255, 159, 64, 1)',
                                'rgba(255, 205, 86, 1)',
                                'rgba(75, 192, 192, 1)',
                                'rgba(54, 162, 235, 1)',
                                'rgba(153, 102, 255, 1)',
                                'rgba(201, 203, 207, 1)'
                            ],

                            borderWidth: 1
                        }]
                    },
                    options: {
                        scales: {
                            y: {
                                beginAtZero: true
                            }
                        }
                    }
                });

            })

    </script>
{% endblock %}